baseurl = "https://vitahlin.github.io"
title = "Vitah Lin"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  author = "Vitah Lin"
  description = "Vitah Lin's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

 # customCSS = ["css/custom.css"]
 # customSCSS = ["scss/custom.scss"]
 # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:linw1225@gmail.com"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/vitahlin"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[params.utterances]
  repo = "vitahlin/hugo-blog-utterances"
  issueTerm = "pathname"
  label = "Comment"
  theme = "github-light"