language: go
go:
  - "1.12" 

git:
  quiet: true
  
# 仓库分支
branches:
  only:
  - develop

before_install:
  - git config --global user.name ${UserName}
  - git config --global user.email ${UserEmail}

install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install

script:
  - cd $TRAVIS_BUILD_DIR/blog/
  - hugo
  - cd public/
  - echo -n www.vitah.net > CNAME
  - git init
  - git status
  - git add .
  - git commit -m "Travis CI Auto Builder $TRAVIS_BUILD_NUMBER"
  - git push --force https://${GithubToken}@${GithubPageRepo} ${GithubBranch}