language: go

git:
  quiet: true
  
# 仓库分支
branches:
  only:
  - hugo

before_install:
  - git config --global user.name ${UserName}
  - git config --global user.email ${UserEmail}

install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install
  - cd $TRAVIS_BUILD_DIR
  - cd blog/
  - git clone https://github.com/dillonzq/LoveIt.git themes/LoveIt

script:
  - hugo
  - cd public/
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder $TRAVIS_BUILD_NUMBER"
  - git push --force https://${GithubToken}@${GithubPageRepo} ${GithubBranch}