.PHONY: build up start stop down status hugo

build:
	docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps

hugo:
	docker-compose exec hugo /bin/bash