.PHONY: build up start stop down status hexo

build:
	docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps

hexo:
	docker-compose exec hexo /bin/sh