name: Github Pages

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on:  ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hugo
          submodule: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - run: ls -a ./hugo
      - run: ls -a ./hugo/themes

      
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        working-directory: ./hugo
        run: |
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./hugo/public
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          cname: vitah.net
