name: Github Pages

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on:  ubuntu-18.04
    steps:
      - name: Checkout hugo branch.
        uses: actions/checkout@v2
        with:
          ref: hugo
          submodules: "true"
          fetch-depth: 1

      - name: Setup hugo enrironment.
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Hugo --minify.
        working-directory: ./hugo
        run: |
          hugo --minify

      - name: Deploy public/ to master branch.
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./hugo/public
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          cname: www.vitah.net
